### ISSUE TITLE
Issue in requirements

### ISSUE THREAD

**Issue by dudeisbrendan03** [mvrozanti/RAT-via-Telegram#50]
cv2 isn't a thing, my bad.

Change `cv2` for `opencv-python`

**Comment by mvrozanti** [comment]
[fixed!](9fca1c504f4be81fd66369a4b052d2f0b8c2ebf5)

**Comment by dudeisbrendan03** [comment]
Thanks

**Comment by mvrozanti** [comment]
@dudeisbrendan03 may I ask, why did you add `--hidden-import ctypes` to compilation? I can't run it for some reason.

**Comment by dudeisbrendan03** [comment]
I might have placed it in the wrong place. Haven't tested it. Need it to stop all those pop-ups about api-*.dll missing.

**Comment by mvrozanti** [comment]
I just noticed you added a dependency, consoletools; which you're hosting on pypi. Can you explain why exactly is this necessary?

**Comment by dudeisbrendan03** [comment]
It's been on there for a while, it's a tool that is used for logging and adding some fancy text on output

**Comment by mvrozanti** [comment]
I think it's a great idea -- small reusable tools -- it's the [suckless-](https://st.suckless.org/) way to do something; but it does add yet another piece of code to look at that can change in parallel with this repo. We already have got python's large `logging` module. Perhaps we should stick to it otherwise I think people would get either suspicious of compiling a RAT with many dependencies or would have to spend a bit of time looking up what's in there. Do you agree?

**Comment by dudeisbrendan03** [comment]
Tbh I just did it for the colours. The project came from me and a couple of friends are working on a large project and the console spits out a load of data, some we didn't want in the console only logged and some needed to be pointed out. So we made a module where you can just classify spam and add colours

**Comment by dudeisbrendan03** [comment]
If you want to remove it go ahead
